### ISSUE TITLE
[L2T] True-And-False Branch in CFG

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#76]
In current CFG implementation, when we need to know whether a child is from the true or false branch of a decision node, we can get TRUE, FALSE, TRUE_FALSE relation. Such a design is very confusing when the type is TRUE_FALSE. We need to know exactly it is TRUE or FALSE.

**Comment by lylytran** [comment]
this is the example of the case TRUE_FALSE branch:
1. if (cond) {
2.    stmtA();
3. }
4. stmtB();
line 4 will be a TRUE_FALSE branch of cond 1, in those cases, the false branch is missing, so it does not make sense to me that line 4 should be consider as a FALSE branch, that's why I assigned it as TRUE_FALSE branch.

**Comment by lylytran** [comment]
in fact, that explicit design is necessary to determine correct branch coverage of a condition node. Other than that, in normal case, I think you can treat TRUE_FALSE node as a FALSE branch.
