### ISSUE TITLE
[L2T] Buggy Generation of Array Length

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#81]
Hi @lylytran,

There is a nullpointer exception (suppressed) when we want to generate an array with length 100. We check the code, finding that array.length report nullpointer exception. The consequence is that array.length can never take effect. Please kindly have a check.

@ZhangHarry please provide an example to Lyly for her convenience. Thanks!

**Comment by ZhangHarry** [comment]
[BigMatrixImpl.zip](https://github.com/sunjun-group/Ziyuan/files/1239245/BigMatrixImpl.zip)
org.apache.commons.math.linear.BigMatrixImpl.getSubMatrix.643.
When the array length ,like selectedColumns.length, is negative, the generated test cases seems strange.

**Comment by lylytran** [comment]
do you still have the log and generated testcases so that I can check?

**Comment by ZhangHarry** [comment]
[BigMatrixImpl.zip](https://github.com/sunjun-group/Ziyuan/files/1241075/BigMatrixImpl.zip)
@lylytran

**Comment by lylytran** [comment]
a few thousand generated methods for Math:
@ZhangHarry : what kind of strange in the testcase did you mean? I imported your given testcases, and it looks fine to me, I don't know what the problem is.

**Comment by ZhangHarry** [comment]
For original vars: [selectedColumns.isNull, selectedColumns.length, selectedRows.length, selectedRows.isNull, this.data.isNull], if the data point is [0.0,-1000.0,8.0,0.0,1.0,], what kind of test case will be generated?  It seems that it will generate selectedRows with length 8, but the length of selectedColumns is a random positive number rather than 0.  But if the data point is [0.0,796.0,-650.0,1.0,1.0,], it would not generate selectedColumns with length 796. The problem is that for many data points, I could not find its responding test case. If the data point is not consistent with test case,  l2t will have trouble. If I make some mistakes, please tell me.
